// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PrimeiroBanco.Models
{
    [Index("nome", Name = "INDICE1")]
    [Index("email", Name = "UQ__Pessoa__AB6E616473F5E147", IsUnique = true)]
    public partial class Pessoa
    {
        [Key]
        public long codigo { get; set; }
        [Required]
        [StringLength(255)]
        public string nome { get; set; }
        [Column(TypeName = "date")]
        public DateTime? dataNasc { get; set; }
        [Column(TypeName = "money")]
        public decimal salario { get; set; }
        [StringLength(150)]
        public string email { get; set; }
        public int estatus { get; set; }
    }
}